spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  security:
    user:
      name: admin
      password: 8506
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/