spring:
  application:
    name: eureka-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # Default to "dev" if not set

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
